import arcade

SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 1024
SCREEN_TITLE = "PyThopoly"
FULLSCREEN = True
BACKGROUND_COLOR = arcade.color.CELADON_GREEN
UPDATES_PER_FRAME = 5

PLAYER_PATH_CLASS = 'player_path'
DICE_CLASS = "dice"

MOVE_TRANSITION_SPEED = 0.05
