import arcade

SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 1024
SCREEN_TITLE = "PyThopoly"
FULLSCREEN = True
BACKGROUND_COLOR = arcade.color.CELADON_GREEN
DICE_SCALE = 4
UPDATES_PER_FRAME = 5

PLAYER_PATH_CLASS = 'player_path'
